### PR TITLE
Connecting Redux and Components

### PR DESCRIPTION
**Pull request by jsm13**
Currently this is just adding the Redux devtools so that you can easily look at state. Next, going to photos into the app component. This may not be the component where you want it but it will be the same pattern you want to use elsewhere

### CODE REVIEW

**Comment by jsm13** [comment]
Second commit injects the photos array into app (though I don't think this is necessarily where you want it)

**Comment by lizardbird** [comment]
So now you've got me thinking - do I actually need two different state items? One for the current Photo being uploaded/edited and the second being photos array pulled from the backend?

**Comment by jsm13** [comment]
Not necessarily, it is alright for a form to keep its own internal state and then dispatch an action which will take care of making the request. It's really when you need to coordinate different components working together that redux comes in really handy

**Comment by lizardbird** [comment]
Okay got it, so each page can set an internal state, and then dispatch an action to update the master state. Maybe trying to implement Redux in the final 24 hours before presentation was a little ambitious... :)

**Comment by jsm13** [comment]
Right, each _can_ have internal state. For something like showing a list of things, there isn't really a good reason and state can come right from redux. Something like a form though that has more state to it might be a hassle to dispatch an actions for every change to the form (good article on the topic [here](https://goshakkk.name/should-i-put-form-state-into-redux/)

These last changes connect the `ShowPhotos` component to redux, provides it the parts of the `photo` bit of state, and puts a little button in for dispatching an action. In practice you might want to dispatch the action from a lifecycle method (or even from another component), just put it in so it was easy to play with dispatching actions

This is a good project for experimenting / exploring. I'm glad you took the jump with redux.

**Comment by lizardbird** [comment]
Am I good to merge the pull request? Thank you so so much for getting in there and digging around.

**Comment by jsm13** [comment]
Yeah, absolutely, you can also take pieces and close the PR if you'd like. Does this help sort out the problem you were having or is there anything I could clarify?

**Comment by lizardbird** [comment]
It does seem to be working - and I moved the fetchPhotos function into the componentDidMount so that it runs automatically. Now I just need to decide how to handle the "current Photo" piece. But I think I am good. THANK YOU!!!!!

**Pull request merged**
